import { GetCharactersResultType } from "@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types";

export interface HandleFavoriteButton {
    character: GetCharactersResultType
    isFavorite: boolean
    removeFavorite: (character: GetCharactersResultType) => void
    addFavorite: (character: GetCharactersResultType) => void
}