'use client'

import { createContext, useState, ReactNode, useContext } from 'react'
import { AppContextProps } from './types'
import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'

const AppContext = createContext<AppContextProps | undefined>(undefined)

export const AppProvider = ({ children }: { children: ReactNode }) => {
    const [favorites, setFavorites] = useState<GetCharactersResultType[]>([])

    const addFavorite = (character: GetCharactersResultType) => {
        setFavorites([...favorites, character])
    }

    const removeFavorite = (character: GetCharactersResultType) => {
        setFavorites(favorites.filter(({ id }) => id !== character.id))
    }

    return <>
        <AppContext.Provider value={{ favorites, addFavorite, removeFavorite }}>
            {children}
        </AppContext.Provider>
    </>
}

export const useApp = () => {
    const context = useContext(AppContext)

    if (!context) {
        throw new Error('useApp must be used within a AppProvider')
    }

    return context
}