import { GetCharactersResultType } from "@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types"

export interface AppContextProps {
    characters: GetCharactersResultType[]
    setSearch: (search: string) => void
}