import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'

export interface AppContextProps {
    favorites: GetCharactersResultType[]
    addFavorite: (character: GetCharactersResultType) => void
    removeFavorite: (character: GetCharactersResultType) => void
}