import { Md5 } from 'ts-md5'
import { GetCharactersType } from './AutoGeneratedTypes/GetCharacters.types'
import { GetCharacterType } from './AutoGeneratedTypes/GetCharacter.types'
import { GetCharacterMarvelAPIProps, GetMarvelAPIProps } from './types'
import { GetComicsFromCharacterType } from './AutoGeneratedTypes/GetComicsFromCharacter.types'

const publicKey = process.env.NEXT_PUBLIC_PUBLICKEY as string
const privateKey = process.env.NEXT_PUBLIC_PRIVATEKEY as string

export const getCharacters = async ({ params }: GetMarvelAPIProps): Promise<GetCharactersType> => {
    const timeStamp = new Date().getTime()

    const response = await fetch(`http://gateway.marvel.com/v1/public/characters?${new URLSearchParams({
        apikey: publicKey,
        ts: timeStamp,
        hash: Md5.hashStr(timeStamp + privateKey + publicKey),
        ...params
    })}`)

    return response.json()
}

export const getCharacter = async ({ id, params }: GetCharacterMarvelAPIProps): Promise<GetCharacterType> => {
    const timeStamp = new Date().getTime()

    const response = await fetch(`http://gateway.marvel.com/v1/public/characters/${id}?${new URLSearchParams({
        apikey: publicKey,
        ts: timeStamp,
        hash: Md5.hashStr(timeStamp + privateKey + publicKey),
        ...params
    })}`)

    return response.json()
}

export const getComicsFromCharacter = async ({ id, params }: GetCharacterMarvelAPIProps): Promise<GetComicsFromCharacterType> => {
    const timeStamp = new Date().getTime()

    const response = await fetch(`http://gateway.marvel.com/v1/public/characters/${id}/comics?${new URLSearchParams({
        apikey: publicKey,
        ts: timeStamp,
        hash: Md5.hashStr(timeStamp + privateKey + publicKey),
        ...params
    })}`)

    return response.json()
}