import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'

export interface FavoritesContextProps {
    favorites: GetCharactersResultType[]
    favoritesIds: number[]
    addFavorite: (character: GetCharactersResultType) => void
    removeFavorite: (character: GetCharactersResultType) => void
    searchFavorites: (search: string) => void
}