import { GetCharactersResultType } from "@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types"

export interface FavoritesContextProps {
    favorites: GetCharactersResultType[]
    favoriteIds: number[]
    addFavorite: (character: GetCharactersResultType) => void
    removeFavorite: (character: GetCharactersResultType) => void
}