import { FC } from 'react'
import Link from 'next/link'
import { useFavorites } from '@/context/FavoritesContext'
import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'
import styles from './index.module.css'

const CharacterCard: FC<GetCharactersResultType> = (props) => {
    const {
        id,
        name,
        thumbnail: {
            path,
            extension,
        }
    } = props
    const { favoritesIds, addFavorite, removeFavorite } = useFavorites()
    const isFavorite = favoritesIds.includes(id)

    const handleFavoriteClick = () => {
        if (isFavorite) {
            removeFavorite(props)
        } else {
            addFavorite(props)
        }
    }

    return <div className={styles.card}>
        <div className={styles.image} style={{ backgroundImage: `url(${path}.${extension})` }}></div>
        <div className={styles.title}>
            <Link href={{ pathname: `/character/${id}` }}>{name}</Link>
            <button onClick={handleFavoriteClick}>
                {isFavorite ? <img src={'/heart-default.png'} alt='Remove from Favorites' title='Remove from Favorites' /> : <img src={'/heart-alt.png'} alt='Add to Favorites' title='Add to Favorites' />}
            </button>
        </div>
    </div>
}

export default CharacterCard