import { FC } from 'react'
import Link from 'next/link'
import { useFavorites } from '@/context/FavoritesContext'
import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'

const CharacterCard: FC<GetCharactersResultType> = (props) => {
    const {
        id,
        name,
        thumbnail: {
            path,
            extension,
        }
    } = props
    const { favoriteIds, addFavorite, removeFavorite } = useFavorites()
    const isFavorite = favoriteIds.includes(id)

    const handleFavoriteClick = () => {
        if (isFavorite) {
            removeFavorite(props)
        } else {
            addFavorite(props)
        }
    }

    if (name === undefined) return <>Loading...</>

    return <>
        <img src={`${path}.${extension}`} alt={name} />
        <h3><Link href={`/character/${id}`}>{name}</Link></h3>
        <button onClick={handleFavoriteClick}>
            {isFavorite ? 'Remove from Favorites' : 'Add to Favorites'}
        </button>
    </>
}

export default CharacterCard