import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { useFavorites } from '@/context/FavoritesContext'
import { getCharacter, getComicsFromCharacter } from '@/utils/MarvelAPI'
import { DEFAULT_CHARACTER_CARD } from '@/constants'
import { GetCharacterResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacter.types'
import { GetComicsFromCharacterResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetComicsFromCharacter.types'

const CharacterPage = () => {
    const { favoritesIds, addFavorite, removeFavorite } = useFavorites()
    const router = useRouter()
    const { id } = router.query
    const currentCharacter = id as unknown as number
    const [character, setCharacter] = useState<GetCharacterResultType>(DEFAULT_CHARACTER_CARD)
    const [comics, setComics] = useState<GetComicsFromCharacterResultType[]>([])
    const isFavorite = favoritesIds.includes(Number(id))

    useEffect(() => {
        const fetchCharacter = async () => {
            const response = await getCharacter({
                id: currentCharacter,
            })

            setCharacter(response.data.results[0])
        }

        const fetchComics = async () => {
            const response = await getComicsFromCharacter({
                id: currentCharacter,
                params: {
                    limit: 20
                }
            })

            setComics(response.data.results)
        }

        if (id) {
            fetchCharacter()
            fetchComics()
        }
    }, [id])

    if (character.name === undefined) return <>Loading...</>

    return <>
        <img src={`${character.thumbnail.path}.${character.thumbnail.extension}`} alt={character.name} />
        <h1>{character.name}</h1>
        <p>{character.description}</p>
        <button onClick={() => (isFavorite ? removeFavorite(character) : addFavorite(character))}>
            {isFavorite ? 'Remove from Favorites' : 'Add to Favorites'}
        </button>
        {!!comics.length && <>
            <h2>Comics</h2>
            <ul>
                {comics.map(comic => (
                    <li key={comic.id}>{comic.title}</li>
                ))}
            </ul>
        </>}
    </>
}

export default CharacterPage