import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'

export interface SearchContextProps {
    characters: GetCharactersResultType[]
    searchTotal: (search: string) => void
    isLoading: boolean
}