import CharacterCard from '@/components/CharacterCard'
import { useEffect, useState } from 'react'
import { GetCharactersResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetCharacters.types'
import { DEFAULT_CHARACTER_CARD, DEFAULT_SEARCH_LIMIT } from '@/constants'
import { getCharacters } from '@/utils/MarvelAPI'

const CharacterList = () => {
    const [characters, setCharacters] = useState<GetCharactersResultType[]>(Array.apply(null, Array(50)).map(() => DEFAULT_CHARACTER_CARD))

    useEffect(() => {
        const fetchCharacters = async () => {
            const response = await getCharacters({
                params: {
                    limit: DEFAULT_SEARCH_LIMIT,
                },
            })

            setCharacters(response.data.results)
        }

        fetchCharacters()
    }, [])

    return <>
        <ul>
            {characters.map((character, key) => (
                <li key={key}>
                    <CharacterCard character={character} />
                </li>
            ))}
        </ul>
    </>
}

export default CharacterList