import { FC } from 'react'
import { GetComicsFromCharacterResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetComicsFromCharacter.types'
import styles from './index.module.css'

const ComicCard: FC<GetComicsFromCharacterResultType> = (props) => {
    const {
        title,
        thumbnail: {
            path,
            extension,
        },
        dates
    } = props

    return <>
        <div className={styles.card}>
            <div className={styles.image} style={{ backgroundImage: `url(${path}.${extension})` }}></div>
            <div className={styles.name}>{title}</div>
            <div className={styles.date}>{dates[0].date.split('-')[0]}</div>
        </div>
    </>
}

export default ComicCard