import '@testing-library/jest-dom'
import { render, screen } from '@testing-library/react'
import ComicCard from '.'
import { GetComicsFromCharacterResultType } from '@/utils/MarvelAPI/AutoGeneratedTypes/GetComicsFromCharacter.types'

describe('ComicCard tests', () => {
    const mockComic: GetComicsFromCharacterResultType = {
        id: 1,
        title: 'Mock Comic',
        dates: [{ type: 'onsaleDate', date: '2023-01-01T00:00:00-0500' }],
        thumbnail: {
            path: 'http://example.com/image',
            extension: 'jpg'
        }
    }

    it('displays the correct title', () => {
        const { asFragment } = render(<ComicCard {...mockComic} />)

        expect(screen.getByText('Mock Comic')).toBeInTheDocument()
        expect(asFragment()).toMatchSnapshot()
    })

    it('displays the correct image', () => {
        const { container, asFragment } = render(<ComicCard {...mockComic} />)
        const imageDiv = container.querySelector('.image')

        expect(imageDiv).toHaveStyle(`background-image: url(http://example.com/image.jpg)`)
        expect(asFragment()).toMatchSnapshot()
    })

    it('displays the correct date', () => {
        const { asFragment } = render(<ComicCard {...mockComic} />)

        expect(screen.getByText('2023')).toBeInTheDocument()
        expect(asFragment()).toMatchSnapshot()
    })
})